---
title: "Internal Assessment 3"
output: pdf_document
---


\begin{center}
{\Large ECON03SEC1}\\
{\Large Department of Economics}\\
{\Large Presidency University, Kolkata}\\
{\large Full Marks: 40}\\
{\large 19/12/2022}
\end{center}


Answer the following questions: [$4 \times 5 = 20$]


1. Using the data `GDP.xlsx`, for any two countries plot separate line charts for the components of GDP (Household Consumption Expenditure, Government final consumption expenditure, Net exports and Gross Capital formation).
2. Suppose that the firm’s production function is $Q = F(K, L) = 50K^{0.5}L^{0.5}$. Suppose, too, that the price of labour $w=5$ and the price of capital $r=20$. What is the cost minimising input bundle if the firm wants to produce 1,000 units per year?
3. What is the average displacement of a manual car with 4 cylinders in the `mtcars.xlsx``` dataset?
4. How does the number of cylinders `cyl` affect the mileage `mpg` for a given horsepower `hp`? Calculate the partial correlation in the `mtcars.xlsx` dataset.

Answer the following questions: [$4 \times 5 = 20$]

5. Calculate the HDI dimension indicies and the HDI using the following formulae $$DimensionIndex = \frac{\text{actual value} - \text{minimum value}}{\text{maximum value} -\text{minimum value}}$$

$$
HDI = (I_{health} \times I_{education} \times I_{income})^{1/3}
$$
for health, income, and education respectively for all the countries. Refer to the following table for the minimum and maximum values:

```{r, echo=FALSE}
kableExtra::kable(
  dplyr::tibble(Dimension = c("Health", "Education", "", "Standard of Living"),
                Indicator = c("Life Expectancy (years", "Expected years of schooling (years",
                              "Mean years of schooling (years)",
                              "GNI percapita (2011 PPP $)"),
                Minimum = c(20, 0 ,0, 100),
                Maximum = c(85, 18, 15, 75000))
)
```

The actual values are in the data. Note that the *knowledge dimension index* is the average of the dimension index for the expected years of schooling, and the mean years of schooling.

6. 